version: 2

jobs:
  build:
    working_directory: ~/testci
    docker:
      - image: svikramjeet/php8.1
        environment:
          POSTGRES_PASSWORD: postgres

    steps:
      - run:
          name: Test
          command: ls

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - api_tests:
          filters:
            branches:
              only:
                - master


