version: 2

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  heroku_deploy_review_app:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME

workflows:
  version: 2
  heroku_deploy:
    jobs:
      - heroku_deploy_review_app:
          filters:
            branches:
              only:
                - test-123/test-heroku-orb


