version: 2

jobs:
  build:
    working_directory: ~/testci

    steps:
      - run:
          name: Test
          command: ls

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

